/**
 * Task Mappers — snake_case (DB) ↔ PascalCase (Frontend)
 */
import type { Task, TaskStatus, TaskPriority } from '../../types';

export const dbToTask = (row: any): Task => ({
    TaskID: row.task_id,
    Title: row.title,
    Description: row.description || '',
    ProjectID: row.project_id,
    AssigneeID: row.assignee_id || '',
    DueDate: row.due_date || '',
    StartDate: row.start_date || '',
    Status: row.status as TaskStatus,
    Priority: row.priority as TaskPriority,
    Phase: row.phase || '',
    StepCode: row.step_code || '',
    TimelineStep: row.step_code || '',
    LegalBasis: row.legal_basis || '',
    OutputDocument: row.output_document || '',
    DurationDays: row.duration_days || 0,
    PredecessorTaskID: row.predecessor_task_id || '',
    ApproverID: row.approver_id || '',
    EstimatedCost: Number(row.estimated_cost) || 0,
    ActualStartDate: row.actual_start_date || '',
    ActualEndDate: row.actual_end_date || '',
    Progress: row.progress || 0,
    ProgressPercent: row.progress || 0,
    SubTasks: row.sub_tasks || [],
    Attachments: row.attachments || [],
    Dependencies: row.dependencies || [],
    IsCritical: row.is_critical || false,
});

export const taskToDb = (t: Partial<Task>) => ({
    ...(t.TaskID !== undefined && { task_id: t.TaskID }),
    ...(t.Title !== undefined && { title: t.Title }),
    ...(t.Description !== undefined && { description: t.Description }),
    ...(t.ProjectID !== undefined && { project_id: t.ProjectID }),
    ...(t.AssigneeID !== undefined && { assignee_id: t.AssigneeID }),
    ...(t.StartDate !== undefined && { start_date: t.StartDate }),
    ...(t.DueDate !== undefined && { due_date: t.DueDate }),
    ...(t.Status !== undefined && { status: t.Status }),
    ...(t.Priority !== undefined && { priority: t.Priority }),
    ...(t.Phase !== undefined && { phase: t.Phase }),
    ...(t.StepCode !== undefined && { step_code: t.StepCode }),
    ...(t.TimelineStep !== undefined && !t.StepCode && { step_code: t.TimelineStep }),
    ...(t.LegalBasis !== undefined && { legal_basis: t.LegalBasis }),
    ...(t.OutputDocument !== undefined && { output_document: t.OutputDocument }),
    ...(t.DurationDays !== undefined && { duration_days: t.DurationDays }),
    ...(t.PredecessorTaskID !== undefined && { predecessor_task_id: t.PredecessorTaskID }),
    ...(t.ApproverID !== undefined && { approver_id: t.ApproverID }),
    ...(t.EstimatedCost !== undefined && { estimated_cost: t.EstimatedCost }),
    ...(t.ActualStartDate !== undefined && { actual_start_date: t.ActualStartDate }),
    ...(t.ActualEndDate !== undefined && { actual_end_date: t.ActualEndDate }),
    ...(t.Progress !== undefined && { progress: t.Progress }),
    ...(t.ProgressPercent !== undefined && { progress: t.ProgressPercent }),
    ...(t.SubTasks !== undefined && { sub_tasks: t.SubTasks }),
    ...(t.Attachments !== undefined && { attachments: t.Attachments }),
    ...(t.Dependencies !== undefined && { dependencies: t.Dependencies }),
    ...(t.IsCritical !== undefined && { is_critical: t.IsCritical }),
});
